import { schema, rules } from '@ioc:Adonis/Core/Validator'

export default class CreateUserValidator {
  public schema = schema.create({
    title: schema.string({ escape: true, trim: true }, [rules.maxLength(255)]),
    firstName: schema.string({ escape: true, trim: true }, [rules.maxLength(255)]),
    lastName: schema.string({ escape: true, trim: true }, [rules.maxLength(255)]),
    houseNameOrNumber: schema.string({ escape: true, trim: true }, [rules.maxLength(255)]),
    postcode: schema.string({ escape: true, trim: true }, [rules.maxLength(255)]),
    mobileNumber: schema.string({ escape: true, trim: true }, [rules.maxLength(255)]),
    email: schema.string({ escape: true, trim: true }, [
      rules.confirmed('emailConfirmation'),
      rules.email({ sanitize: true }),
      rules.maxLength(255),
      rules.unique({ table: 'users', column: 'email', caseInsensitive: true }),
    ]),
    additionalParentOrGuardian: schema.boolean(),
    alternateTitle: schema.string.optional({ escape: true, trim: true }, [
      rules.requiredWhen('additionalParentOrGuardian', 'in', [true, 'true', 1, '1']),
      rules.maxLength(255),
    ]),
    alternateFirstName: schema.string.optional({ escape: true, trim: true }, [
      rules.requiredWhen('additionalParentOrGuardian', 'in', [true, 'true', 1, '1']),
      rules.maxLength(255),
    ]),
    alternateLastName: schema.string.optional({ escape: true, trim: true }, [
      rules.requiredWhen('additionalParentOrGuardian', 'in', [true, 'true', 1, '1']),
      rules.maxLength(255),
    ]),
    alternateHouseNameOrNumber: schema.string.optional({ escape: true, trim: true }, [
      rules.requiredWhen('additionalParentOrGuardian', 'in', [true, 'true', 1, '1']),
      rules.maxLength(255),
    ]),
    alternatePostcode: schema.string.optional({ escape: true, trim: true }, [
      rules.requiredWhen('additionalParentOrGuardian', 'in', [true, 'true', 1, '1']),
      rules.maxLength(255),
    ]),
    alternateMobileNumber: schema.string.optional({ escape: true, trim: true }, [
      rules.requiredWhen('additionalParentOrGuardian', 'in', [true, 'true', 1, '1']),
      rules.maxLength(255),
    ]),
    alternateEmail: schema.string.optional({ escape: true, trim: true }, [
      rules.requiredWhen('additionalParentOrGuardian', 'in', [true, 'true', 1, '1']),
      rules.email({ sanitize: true }),
      rules.maxLength(255),
      rules.fieldNotMatch({ comparisonFieldName: 'email' }),
    ]),
    password: schema.string({}, [rules.minLength(8), rules.maxLength(255), rules.confirmed('passwordConfirmation')]),
  })

  public messages = {
    'title.string': `Field '{{ field }}' must be a string`,
    'title.required': `Field '{{ field }}' is required`,
    'title.maxLength': `Field '{{ field }}' must be a maximum of 255 characters`,
    'firstName.string': `Field '{{ field }}' must be a string`,
    'firstName.required': `Field '{{ field }}' is required`,
    'firstName.maxLength': `Field '{{ field }}' must be a maximum of 255 characters`,
    'lastName.string': `Field '{{ field }}' must be a string`,
    'lastName.required': `Field '{{ field }}' is required`,
    'lastName.maxLength': `Field '{{ field }}' must be a maximum of 255 characters`,
    'houseNameOrNumber.string': `Field '{{ field }}' must be a string`,
    'houseNameOrNumber.required': `Field '{{ field }}' is required`,
    'houseNameOrNumber.maxLength': `Field '{{ field }}' must be a maximum of 255 characters`,
    'postcode.string': `Field '{{ field }}' must be a string`,
    'postcode.required': `Field '{{ field }}' is required`,
    'postcode.maxLength': `Field '{{ field }}' must be a maximum of 255 characters`,
    'mobileNumber.string': `Field '{{ field }}' must be a string`,
    'mobileNumber.required': `Field '{{ field }}' is required`,
    'mobileNumber.maxLength': `Field '{{ field }}' must be a maximum of 255 characters`,
    'email.string': `Field '{{ field }}' must be a string`,
    'email.required': `Field '{{ field }}' is required`,
    'email.email': `Field '{{ field }}' must be a valid email address`,
    'email.maxLength': `Field '{{ field }}' must be a maximum of 255 characters`,
    'email.unique': `Field '{{ field }}' value is already in use`,
    'email.confirmed': `Field '{{ field }}' must match field '{{ field }}Confirmation'`,
    'additionalParentOrGuardian.boolean': `Field '{{ field }}' must be a boolean`,
    'additionalParentOrGuardian.required': `Field '{{ field }}' is required`,
    'alternateTitle.string': `Field '{{ field }}' must be a string`,
    'alternateTitle.requiredWhen': `Field '{{ field }}' is required when field 'additionalParentOrGuardian' is true`,
    'alternateTitle.maxLength': `Field '{{ field }}' must be a maximum of 255 characters`,
    'alternateFirstName.string': `Field '{{ field }}' must be a string`,
    'alternateFirstName.requiredWhen': `Field '{{ field }}' is required when field 'additionalParentOrGuardian' is true`,
    'alternateFirstName.maxLength': `Field '{{ field }}' must be a maximum of 255 characters`,
    'alternateLastName.string': `Field '{{ field }}' must be a string`,
    'alternateLastName.requiredWhen': `Field '{{ field }}' is required when field 'additionalParentOrGuardian' is true`,
    'alternateLastName.maxLength': `Field '{{ field }}' must be a maximum of 255 characters`,
    'alternateHouseNameOrNumber.string': `Field '{{ field }}' must be a string`,
    'alternateHouseNameOrNumber.requiredWhen': `Field '{{ field }}' is required when field 'additionalParentOrGuardian' is true`,
    'alternateHouseNameOrNumber.maxLength': `Field '{{ field }}' must be a maximum of 255 characters`,
    'alternatePostcode.string': `Field '{{ field }}' must be a string`,
    'alternatePostcode.requiredWhen': `Field '{{ field }}' is required when field 'additionalParentOrGuardian' is true`,
    'alternatePostcode.maxLength': `Field '{{ field }}' must be a maximum of 255 characters`,
    'alternateMobileNumber.string': `Field '{{ field }}' must be a string`,
    'alternateMobileNumber.requiredWhen': `Field '{{ field }}' is required when field 'additionalParentOrGuardian' is true`,
    'alternateMobileNumber.maxLength': `Field '{{ field }}' must be a maximum of 255 characters`,
    'alternateEmail.string': `Field '{{ field }}' must be a string`,
    'alternateEmail.requiredWhen': `Field '{{ field }}' is required when field 'additionalParentOrGuardian' is true`,
    'alternateEmail.email': `Field '{{ field }}' must be a valid email address`,
    'alternateEmail.maxLength': `Field '{{ field }}' must be a maximum of 255 characters`,
    'alternateEmail.fieldNotMatch': `Field '{{ field }}' must not have the same value as field 'email'`,
    'password.string': `Field '{{ field }}' must be a string`,
    'password.required': `Field '{{ field }}' is required`,
    'password.minLength': `Field '{{ field }}' must be at least 8 characters`,
    'password.maxLength': `Field '{{ field }}' must be no more than 50 characters`,
    'password.confirmed': `Field '{{ field }}' must match field '{{ field }}Confirmation'`,
  }
}
